import jsPDF from 'jspdf';
import JSZip from 'jszip';

interface Supplier {
  urn: string;
  name: string;
  status: string;
  lastChecked: string;
}

// Perfect checkmark with your settings
function drawCheckmarkBadge(doc: jsPDF, x: number, y: number, size: number) {
  // Green circle
  doc.setFillColor(22, 163, 74);
  doc.circle(x, y, size, 'F');

  // White border
  doc.setDrawColor(255, 255, 255);
  doc.setLineWidth(2.5);
  doc.circle(x, y, size - 2, 'S');

  // Perfect checkmark settings from test environment
  const verticalOffset = size * 0.00;      // Your setting
  const horizontalOffset = size * -0.02;   // Your setting
  const lineWidth = 3.5;                   // Your setting (14px / 4)

  doc.setDrawColor(255, 255, 255);
  doc.setLineWidth(lineWidth);
  doc.setLineCap('round');
  doc.setLineJoin('round');

  const checkWidth = size * 0.7;

  const leftX = x - checkWidth * 0.3 + horizontalOffset;
  const leftY = y + verticalOffset;
  const midX = x - checkWidth * 0.05 + horizontalOffset;
  const midY = y + checkWidth * 0.35 + verticalOffset;
  const rightX = x + checkWidth * 0.4 + horizontalOffset;
  const rightY = y - checkWidth * 0.3 + verticalOffset;

  doc.line(leftX, leftY, midX, midY);
  doc.line(midX, midY, rightX, rightY);
}

// Generate single PDF
export function generatePDF(supplier: Supplier, companyName: string) {
  const doc = new jsPDF();

  // === HEADER ===
  doc.setFillColor(30, 64, 175);
  doc.rect(0, 0, 210, 45, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text(companyName, 105, 20, { align: 'center' });

  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text('AWRS Verification Record', 105, 32, { align: 'center' });

  // === CHECKMARK ===
  drawCheckmarkBadge(doc, 105, 75, 18);

  // === STATUS ===
  doc.setTextColor(22, 163, 74);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('AWRS STATUS: APPROVED', 105, 110, { align: 'center' });

  // === DIVIDER ===
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.5);
  doc.line(30, 125, 180, 125);

  // === SUPPLIER DETAILS ===
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Supplier Information:', 30, 145);

  const detailsY = 160;
  const lineHeight = 12;

  doc.setFontSize(11);

  doc.setFont('helvetica', 'bold');
  doc.text('Business Name:', 30, detailsY);
  doc.setFont('helvetica', 'normal');
  const nameLines = doc.splitTextToSize(supplier.name, 110);
  doc.text(nameLines, 75, detailsY);

  doc.setFont('helvetica', 'bold');
  doc.text('AWRS URN:', 30, detailsY + lineHeight);
  doc.setFont('helvetica', 'normal');
  doc.text(supplier.urn, 75, detailsY + lineHeight);

  doc.setFont('helvetica', 'bold');
  doc.text('Status:', 30, detailsY + lineHeight * 2);
  doc.setTextColor(22, 163, 74);
  doc.setFont('helvetica', 'bold');
  doc.text(supplier.status, 75, detailsY + lineHeight * 2);

  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.text('Check Date:', 30, detailsY + lineHeight * 3);
  doc.setFont('helvetica', 'normal');
  doc.text(new Date(supplier.lastChecked).toLocaleDateString('en-GB'), 75, detailsY + lineHeight * 3);

  // === DIVIDER ===
  doc.setDrawColor(220, 220, 220);
  doc.line(30, 208, 180, 208);

  // === STATEMENT ===
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  doc.setFont('helvetica', 'normal');

  const statement = `This record confirms that on ${new Date(supplier.lastChecked).toLocaleDateString('en-GB')}, the AWRS URN above was checked against the HMRC AWRS register and the status was found to be "${supplier.status}".`;

  const lines = doc.splitTextToSize(statement, 150);
  doc.text(lines, 30, 223);

  // === FOOTER (moved up since disclaimer removed) ===
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.setFont('helvetica', 'normal');
  doc.text('Record generated by AWRS Compliance Portal', 105, 260, { align: 'center' });
  doc.text(`Record ID: ${supplier.urn}-${Date.now()}`, 105, 267, { align: 'center' });
  doc.text(`Generated: ${new Date().toLocaleString('en-GB')}`, 105, 274, { align: 'center' });

  // Download
  const fileName = `AWRS-Record-${supplier.name.replace(/[^a-z0-9]/gi, '-')}-${supplier.urn}.pdf`;
  doc.save(fileName);
}


// Generate bulk PDFs
export async function generateBulkPDF(suppliers: Supplier[], companyName: string) {

  const zip = new JSZip();
  let pdfCount = 0;

  for (let i = 0; i < suppliers.length; i++) {
    const supplier = suppliers[i];

    try {
      const doc = new jsPDF();

      // === HEADER ===
      doc.setFillColor(30, 64, 175);
      doc.rect(0, 0, 210, 45, 'F');

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(28);
      doc.setFont('helvetica', 'bold');
      doc.text(companyName, 105, 20, { align: 'center' });

      doc.setFontSize(14);
      doc.setFont('helvetica', 'normal');
      doc.text('AWRS Verification Record', 105, 32, { align: 'center' });

      // === CHECKMARK ===
      drawCheckmarkBadge(doc, 105, 75, 18);

      // === STATUS ===
      doc.setTextColor(22, 163, 74);
      doc.setFontSize(22);
      doc.setFont('helvetica', 'bold');
      doc.text('AWRS STATUS: APPROVED', 105, 110, { align: 'center' });

      // === DIVIDER ===
      doc.setDrawColor(220, 220, 220);
      doc.setLineWidth(0.5);
      doc.line(30, 125, 180, 125);

      // === DETAILS ===
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(13);
      doc.setFont('helvetica', 'bold');
      doc.text('Supplier Information:', 30, 145);

      const detailsY = 160;
      const lineHeight = 12;

      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text('Business Name:', 30, detailsY);
      doc.setFont('helvetica', 'normal');
      const nameLines = doc.splitTextToSize(supplier.name, 110);
      doc.text(nameLines, 75, detailsY);

      doc.setFont('helvetica', 'bold');
      doc.text('AWRS URN:', 30, detailsY + lineHeight);
      doc.setFont('helvetica', 'normal');
      doc.text(supplier.urn, 75, detailsY + lineHeight);

      doc.setFont('helvetica', 'bold');
      doc.text('Status:', 30, detailsY + lineHeight * 2);
      doc.setTextColor(22, 163, 74);
      doc.setFont('helvetica', 'bold');
      doc.text(supplier.status, 75, detailsY + lineHeight * 2);

      doc.setTextColor(0, 0, 0);
      doc.setFont('helvetica', 'bold');
      doc.text('Check Date:', 30, detailsY + lineHeight * 3);
      doc.setFont('helvetica', 'normal');
      doc.text(new Date(supplier.lastChecked).toLocaleDateString('en-GB'), 75, detailsY + lineHeight * 3);

      // === DIVIDER ===
      doc.setDrawColor(220, 220, 220);
      doc.line(30, 208, 180, 208);

      // === STATEMENT ===
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      doc.setFont('helvetica', 'normal');

      const statement = `This record confirms that on ${new Date(supplier.lastChecked).toLocaleDateString('en-GB')}, the AWRS URN above was checked against the HMRC AWRS register and the status was found to be "${supplier.status}".`;

      const lines = doc.splitTextToSize(statement, 150);
      doc.text(lines, 30, 223);

      // === FOOTER ===
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text('Record generated by AWRS Compliance Portal', 105, 260, { align: 'center' });
      doc.text(`Record ID: ${supplier.urn}-${Date.now()}`, 105, 267, { align: 'center' });

      // Generate PDF blob
      const pdfBlob = doc.output('blob');

      // Create UNIQUE filename with index to prevent overwrites
      const sanitizedName = supplier.name.replace(/[^a-z0-9\s-]/gi, '').replace(/\s+/g, '-');
      const uniqueId = Date.now() + i; // Add index for uniqueness
      const fileName = `${i + 1}-${sanitizedName}-${supplier.urn}-${uniqueId}.pdf`;

      zip.file(fileName, pdfBlob);
      pdfCount++;

      // Small delay to ensure unique timestamps
      await new Promise(resolve => setTimeout(resolve, 10));

    } catch (error) {
      console.error(`❌ Error generating PDF for ${supplier.name}:`, error);
    }
  }

  // Generate ZIP
  const zipBlob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 }
  });

  // Download
  const url = URL.createObjectURL(zipBlob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `AWRS-Records-${new Date().toISOString().split('T')[0]}-${pdfCount}files.zip`;
  link.click();

  // Cleanup
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}


